### ISSUE TITLE
How to listen for map events?

### ISSUE THREAD

**Issue by JoseGoncalves** [inocan-group/vue3-google-maps#1]
Hi, thanks for providing components to interact with Google Maps using Vue 3!

Can you please provide an example on how to intercept/handle map events like `zoom_changed` and `center_changed` ?

**Comment by JoseGoncalves** [comment]
I was able to set this up with the following code:

```vue
<template>
  <GoogleMap id="map" ref="mapRef" :api-key="map.key" :center="map.center" :zoom="map.zoom" />
</template>

<script>
import { ref, watchEffect } from 'vue';
import { GoogleMap } from 'vue3-google-map';

export default {
  components: { GoogleMap },

  setup() {
    const map = {
      key: 'My_Google_Key',
      center: {
        lat: 38.735086,
        lng: -9.141247
      },
      zoom: 13
    };

    const mapRef = ref(null);

    const stopWatch = watchEffect(() => {
      const isReady = mapRef.value ? mapRef.value.ready : false;
      if (!isReady) return;
      const gmap = mapRef.value.map;
      gmap.addListener('zoom_changed', () => {
        console.log('Map: Zoom:', gmap.getZoom());
      });
      gmap.addListener('center_changed', () => {
        const center = gmap.getCenter();
        console.log('Map: Center: (', center.lat(), ',', center.lng(), ')');
      });
      stopWatch();
    });

    return { map, mapRef };
  }
};
</script>

<style>
html,
body,
#app,
#map {
  height: 100%;
}

body {
  margin: 0;
}
</style>
```

Is this the way that you recommend?
Shouldn't be better to hide this setup from the plugin user with custom events setup inside the `GoogleMap` component?

**Comment by HusamIbrahim** [comment]
Hi @JoseGoncalves,
Glad you found a way to work around this issue but you're right we should expose these events through the `GoogleMap` component. That should be implemented very soon.

**Comment by JoseGoncalves** [comment]
Hi @HusamIbrahim. Looking forward to have the map events exposed on the `GoogleMap` component.
Meanwhile, I'm currently using a slightly more optimized setup to listen for those events:

```vue
<script>
import { ref, watch, onMounted } from 'vue';
import { GoogleMap } from 'vue3-google-map';

export default {
  components: { GoogleMap },

  setup() {
    /* ... */
    const mapRef = ref(null);

    onMounted(() => {
      watch(() => mapRef.value.ready, (isReady) => {
        if (!isReady) return;
        const gmap = mapRef.value.map;
        gmap.addListener('zoom_changed', () => {
          console.log('Map: Zoom:', gmap.getZoom());
        });
        gmap.addListener('center_changed', () => {
          const center = gmap.getCenter();
          console.log('Map: Center: (', center.lat(), ',', center.lng(), ')');
        });
      });
    });

    return { map, mapRef };
  }
};
</script>
```

**Comment by HusamIbrahim** [comment]
This landed in `v0.2.0`.

**Comment by JoseGoncalves** [comment]
I've tried and works fine. Thanks!

This is my working setup with `v0.2.0`:
```vue
<template>
	<GoogleMap id="map" ref="mapRef" :api-key="map.key"
                :center="map.center" :zoom="map.zoom" 
		@zoom_changed="zoomChanged" @center_changed="centerChanged"
	/>
</template>

<script>
import { ref } from 'vue';
import { GoogleMap } from 'vue3-google-map';

export default {
	components: { GoogleMap },

	setup() {
		const map = {
			key: 'My_Google_Key',
			center: {
                                lat: 38.735086,
                                lng: -9.141247
			},
			zoom: 13
		};

		const mapRef = ref(null);

		function zoomChanged() {
			const gmap = mapRef.value.map;
			console.log('Map: Zoom', gmap.getZoom());
		}

		function centerChanged() {
			const gmap = mapRef.value.map;
			const center = gmap.getCenter();
			console.log('Map: Center: (', center.lat(), ',', center.lng(), ')');
		}

		return { map, mapRef, zoomChanged, centerChanged };
	}
};
</script>

<style>
html,
body,
#app,
#map {
	height: 100%;
}

body {
	margin: 0;
}
</style>
```

**Comment by MachariaK** [comment]
How do you get the location(lat & lng) of a clicked position on the map?

**Comment by agnaldo111** [comment]
Is there a way, to catch the polyline points changed ?

**Comment by AndreMCCarvalho** [comment]
Hello, sorry for the very very late reply. I'm new to Vue and I'm new to the library, in all of your snippets I see you use mapRef.value.map. My question is this .map how do you know it has to be a .map? Is it because the variable is called map or the id is map? How would you change that or how it work for a circle? Thanks

**Comment by annerland** [comment]
> Hello, sorry for the very very late reply. I'm new to Vue and I'm new to the library, in all of your snippets I see you use mapRef.value.map. My question is this .map how do you know it has to be a .map? Is it because the variable is called map or the id is map? How would you change that or how it work for a circle? Thanks

@AndreMCCarvalho
This library uses google maps api behind it, on google maps api (you can check here https://developers.google.com/maps/documentation/javascript/reference/map).
The map itself has this property inside the obj.

To be able to see it you would need to create a ref and set it to the component like this:

```vue
<script>
import { GoogleMap } from 'vue3-google-map';
const mapObject = ref(null);
</script>

<template>
<GoogleMap
   ref="mapObject"
   ...props
/>
</template>
```

To access the content inside mapObject you will need to create a **watch** effect so you will be able to listen when the map is fully rendered.

```js
watch(() => [ mapObject.value?.ready ], (ready) => {
   console.log(mapObject.value.map);
});
```

**Comment by JoseGoncalves** [comment]
Hi @annerland. You're welcome!

You can also check a demo project that I've setup at https://github.com/JoseGoncalves/vue-google-maps
